INFERANALYZE= /usr/local/Cellar/infer/0.6.0/libexec/infer/lib/python/inferlib/../../../bin/InferAnalyze $(INFER_OPTIONS) -results_dir '/Users/darrengu/songsandhymnsoflife/infer-out'

OBJECTS=cl1 cl2 cl3 cl4 cl5 cl6 cl7 cl8 cl9 cl10 cl11 cl12 cl13 cl14 cl15 cl16 cl17 cl18 cl19 cl20 cl21 cl22 cl23 cl24 cl25 cl26 cl27 cl28 cl29 cl30 cl31 cl32 cl33 cl34 cl35 cl36 cl37 cl38 cl39 cl40 cl41 cl42 cl43 cl44 cl45 cl46 cl47 cl48 cl49 cl50 cl51 cl52 cl53 cl54 cl55 cl56 cl57 cl58 cl59 cl60 cl61 cl62 cl63 cl64 cl65 cl66 cl67 cl68 cl69 cl70 cl71 cl72 cl73 cl74 cl75 cl76 

default: test

all: test

test: $(OBJECTS)
	echo ""
cl1 : 
	$(INFERANALYZE) -cluster xcl1.cluster >cl1

cl2 : 
	$(INFERANALYZE) -cluster xcl2.cluster >cl2

cl3 : 
	$(INFERANALYZE) -cluster xcl3.cluster >cl3

cl4 : 
	$(INFERANALYZE) -cluster xcl4.cluster >cl4

cl5 : 
	$(INFERANALYZE) -cluster xcl5.cluster >cl5

cl6 : 
	$(INFERANALYZE) -cluster xcl6.cluster >cl6

cl7 : 
	$(INFERANALYZE) -cluster xcl7.cluster >cl7

cl8 : 
	$(INFERANALYZE) -cluster xcl8.cluster >cl8

cl9 : 
	$(INFERANALYZE) -cluster xcl9.cluster >cl9

cl10 : 
	$(INFERANALYZE) -cluster xcl10.cluster >cl10

cl11 : 
	$(INFERANALYZE) -cluster xcl11.cluster >cl11

cl12 : 
	$(INFERANALYZE) -cluster xcl12.cluster >cl12

cl13 : 
	$(INFERANALYZE) -cluster xcl13.cluster >cl13

cl14 : 
	$(INFERANALYZE) -cluster xcl14.cluster >cl14

cl15 : 
	$(INFERANALYZE) -cluster xcl15.cluster >cl15

cl16 : 
	$(INFERANALYZE) -cluster xcl16.cluster >cl16

cl17 : 
	$(INFERANALYZE) -cluster xcl17.cluster >cl17

cl18 : 
	$(INFERANALYZE) -cluster xcl18.cluster >cl18

cl19 : 
	$(INFERANALYZE) -cluster xcl19.cluster >cl19

cl20 : 
	$(INFERANALYZE) -cluster xcl20.cluster >cl20

cl21 : 
	$(INFERANALYZE) -cluster xcl21.cluster >cl21

cl22 : 
	$(INFERANALYZE) -cluster xcl22.cluster >cl22

cl23 : 
	$(INFERANALYZE) -cluster xcl23.cluster >cl23

cl24 : 
	$(INFERANALYZE) -cluster xcl24.cluster >cl24

cl25 : 
	$(INFERANALYZE) -cluster xcl25.cluster >cl25

cl26 : 
	$(INFERANALYZE) -cluster xcl26.cluster >cl26

cl27 : 
	$(INFERANALYZE) -cluster xcl27.cluster >cl27

cl28 : 
	$(INFERANALYZE) -cluster xcl28.cluster >cl28

cl29 : 
	$(INFERANALYZE) -cluster xcl29.cluster >cl29

cl30 : 
	$(INFERANALYZE) -cluster xcl30.cluster >cl30

cl31 : 
	$(INFERANALYZE) -cluster xcl31.cluster >cl31

cl32 : 
	$(INFERANALYZE) -cluster xcl32.cluster >cl32

cl33 : 
	$(INFERANALYZE) -cluster xcl33.cluster >cl33

cl34 : 
	$(INFERANALYZE) -cluster xcl34.cluster >cl34

cl35 : cl18 cl34
	$(INFERANALYZE) -cluster xcl35.cluster >cl35

cl36 : cl35
	$(INFERANALYZE) -cluster xcl36.cluster >cl36

cl37 : cl34
	$(INFERANALYZE) -cluster xcl37.cluster >cl37

cl38 : cl34 cl37
	$(INFERANALYZE) -cluster xcl38.cluster >cl38

cl39 : cl34
	$(INFERANALYZE) -cluster xcl39.cluster >cl39

cl40 : cl29
	$(INFERANALYZE) -cluster xcl40.cluster >cl40

cl41 : cl34
	$(INFERANALYZE) -cluster xcl41.cluster >cl41

cl42 : cl31 cl34
	$(INFERANALYZE) -cluster xcl42.cluster >cl42

cl43 : cl42
	$(INFERANALYZE) -cluster xcl43.cluster >cl43

cl44 : cl32 cl34 cl37
	$(INFERANALYZE) -cluster xcl44.cluster >cl44

cl45 : 
	$(INFERANALYZE) -cluster xcl45.cluster >cl45

cl46 : 
	$(INFERANALYZE) -cluster xcl46.cluster >cl46

cl47 : 
	$(INFERANALYZE) -cluster xcl47.cluster >cl47

cl48 : 
	$(INFERANALYZE) -cluster xcl48.cluster >cl48

cl49 : cl34 cl47 cl48
	$(INFERANALYZE) -cluster xcl49.cluster >cl49

cl50 : 
	$(INFERANALYZE) -cluster xcl50.cluster >cl50

cl51 : 
	$(INFERANALYZE) -cluster xcl51.cluster >cl51

cl52 : 
	$(INFERANALYZE) -cluster xcl52.cluster >cl52

cl53 : 
	$(INFERANALYZE) -cluster xcl53.cluster >cl53

cl54 : 
	$(INFERANALYZE) -cluster xcl54.cluster >cl54

cl55 : cl51 cl54
	$(INFERANALYZE) -cluster xcl55.cluster >cl55

#[cl56] missing dependency to app/build/generated/source/apt/debug/com/church/psalm/di/DaggerDaggerComponent.java
#[cl56] missing dependency to app/src/main/java/com/church/psalm/di/DaggerModule.java
cl56 : cl3 cl4 cl7 cl12 cl13 cl15 cl16 cl34 cl49 cl52 cl55
	$(INFERANALYZE) -cluster xcl56.cluster >cl56

cl57 : cl30 cl34 cl37 cl44 cl56
	$(INFERANALYZE) -cluster xcl57.cluster >cl57

cl58 : cl30 cl41 cl49 cl56
	$(INFERANALYZE) -cluster xcl58.cluster >cl58

cl59 : cl58
	$(INFERANALYZE) -cluster xcl59.cluster >cl59

cl60 : cl49 cl58
	$(INFERANALYZE) -cluster xcl60.cluster >cl60

cl61 : cl49 cl58
	$(INFERANALYZE) -cluster xcl61.cluster >cl61

cl62 : cl49 cl58
	$(INFERANALYZE) -cluster xcl62.cluster >cl62

cl63 : cl49 cl58
	$(INFERANALYZE) -cluster xcl63.cluster >cl63

cl64 : cl49 cl58
	$(INFERANALYZE) -cluster xcl64.cluster >cl64

cl65 : cl49 cl58
	$(INFERANALYZE) -cluster xcl65.cluster >cl65

cl66 : cl49 cl58
	$(INFERANALYZE) -cluster xcl66.cluster >cl66

cl67 : cl49 cl58
	$(INFERANALYZE) -cluster xcl67.cluster >cl67

cl68 : cl49 cl58
	$(INFERANALYZE) -cluster xcl68.cluster >cl68

cl69 : cl49 cl58
	$(INFERANALYZE) -cluster xcl69.cluster >cl69

cl70 : cl49 cl58
	$(INFERANALYZE) -cluster xcl70.cluster >cl70

cl71 : cl30 cl45 cl49 cl56 cl60 cl61 cl62 cl63 cl64 cl65 cl66 cl67 cl68 cl69 cl70
	$(INFERANALYZE) -cluster xcl71.cluster >cl71

cl72 : cl30 cl56
	$(INFERANALYZE) -cluster xcl72.cluster >cl72

cl73 : cl72
	$(INFERANALYZE) -cluster xcl73.cluster >cl73

cl74 : cl30 cl45 cl55 cl56 cl72
	$(INFERANALYZE) -cluster xcl74.cluster >cl74

cl75 : cl30 cl55 cl56 cl72 cl74
	$(INFERANALYZE) -cluster xcl75.cluster >cl75

cl76 : cl75
	$(INFERANALYZE) -cluster xcl76.cluster >cl76


clean:
	rm -f $(OBJECTS)
